### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by acarranoqovery**

### CODE REVIEW

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery []() preview a6408b01-0d31-4290-8478-506871e02488 | [local-demo](https://console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/54712864-5d65-4813-aaf2-8e8dcc7d6046/environment/a6408b01-0d31-4290-8478-506871e02488/services/general) |
| /qovery []() preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> One day they will all understand

**Comment by mzottola** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] terraform-env - Update README.md - 2024-12-04T19:06:28Z](https://console.qovery.com/organization/3d542888-3d2c-474a-b1ad-712556db66da/project/72ebf583-114b-4665-a506-bc10ad99144a/environment/bb9906bc-9d1f-449a-941f-bf1319b796d8/services/general)

 Another comment will be posted when deployments are finished

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] local-demo - Update README.md - 2024-12-04T19:07:06Z](https://console.qovery.com/organization/141c07c8-0dd9-4623-983b-3fdd61867255/project/54712864-5d65-4813-aaf2-8e8dcc7d6046/environment/967359f8-91ac-4af4-a77f-26a1e1a7ca9c/services/general)

 Another comment will be posted when deployments are finished

**Comment by acarranoqovery** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [front](https://1-front-local-demo.z809f9644.rustrocks.cloud)

**Pull request merged**
